### ISSUE TITLE
Zoomed in on Mobile Devices and Menu Is Not Working

### ISSUE THREAD

**Issue by krustymk** [DevelopGravity/Fluid-MC-Stats#21] opened 2015-01-07 17:36 UTC
When i install to a root folder it works fine

**Comment by ZacharyDuBois** [comment] 2015-01-08 04:33
Do you know what menu buttons aren't working or is it all of them. I thought I fixed this in 372fb82f362bb364602b833e0581e66017a6806f but, I might not have. As for zoomed, could you screen shot it?

On Xcode's iOS simulator, I was not able to reproduce the zoomed feel on the following:

iPhone 6 Plus:
![ios simulator screen shot jan 7 2015 11 28 47 pm](https://cloud.githubusercontent.com/assets/2458289/5657898/48c17d0e-96c5-11e4-90ff-f8a9c5171fde.png)

iPhone 5:
![ios simulator screen shot jan 7 2015 11 29 42 pm](https://cloud.githubusercontent.com/assets/2458289/5657904/5c0ef940-96c5-11e4-8df9-4601d5161edb.png)

And iPad Air:
![ios simulator screen shot jan 7 2015 11 32 12 pm](https://cloud.githubusercontent.com/assets/2458289/5657906/6a6de1e0-96c5-11e4-9bee-329bbbce5e5a.png)

As for the menubar CSS bug you see on the iPad Air, that I see you opened in it's own issue #22 :)

**Comment by krustymk** [comment] 2015-01-08 11:07
The look you have above is the zoomed look I am referring to.
The three lines you click for the drop down menu do nothing, no menu appears. But only when the site is in a sub folder. Full size, each individual link works.

**Comment by ZacharyDuBois** [comment] 2015-01-10 21:33
My test site is currently in a subdirectory and I cannot reproduce:

![ios simulator screen shot jan 10 2015 4 30 12 pm](https://cloud.githubusercontent.com/assets/2458289/5693343/48bfb956-98e6-11e4-815a-b29e7792fd51.png)
![ios simulator screen shot jan 10 2015 4 31 35 pm](https://cloud.githubusercontent.com/assets/2458289/5693344/48d04280-98e6-11e4-95d5-c2887775b3df.png)

The custom links do not appear on small screens due to the version of Bootstrap we are using. This will be fixed in v0.3.0 with the new interface though.

**Comment by krustymk** [comment] 2015-01-11 01:20
http://theamigos.co.uk/stats/ 
go there and its produced for you, Ill give you ftp access to that folder if you wish

**Comment by ZacharyDuBois** [comment] 2015-01-11 02:00
AH, this is related to your other issue, #22. The JavaScript is not loading at the bottom because the entire bottom of the page is failing to load.

![screen shot 2015-01-10 at 8 59 32 pm](https://cloud.githubusercontent.com/assets/2458289/5694055/aa9e7304-990b-11e4-8712-3bab4fa82b0c.png)

**Comment by ZacharyDuBois** [comment] 2015-01-15 03:01
Fixed :)

**Closed by ZacharyDuBois** 2015-01-15 03:01 UTC
Labels: bug, HTML/CSS/JS, Not Reproducible, PHP
